#!/usr/bin/env python3
import time
def scroll(line):
  n = 16
  sections = [line[i:i+n] for i in range(0, len(line), n)]
  for section in range(0,int(len(sections)/2),2):
    #lcd.message(sections[section])
    #lcd.message(sections[section+1])
    print(sections[section])
    print(sections[section+1])
    time.sleep(0.05)

message = """sfkfhsdkfsdfsdffjfhsd sfds
sdfdsfhdsjkf
sfdsfhkfdshjfdhfjfsdjhfdsdfsjhfdsjkh
fsdfdsfdjkhsdjkh
sdfdshs"""
scroll(message)
