#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time
pins = [17,27,22,10,9,11,5,6]
def setup_pins(pins):
    GPIO.setmode(GPIO.BCM) #set pin mapping
    GPIO.setup(pins, GPIO.OUT) #set output
    GPIO.output(pins,0) #set everything off
setup_pins(pins)

def flash(pin,amount):
    GPIO.output(pin,1)
    time.sleep(amount)
    GPIO.output(pin,0)
    time.sleep(0.1)
print(pins)
for pin in pins:
    print(pin)
    flash(pin,0.1)
GPIO.output(pins,0) #set everything off

